version: '3.1'
services:
  db:
    image: postgres:9.5
    container_name: db
    env_file: ./docker/.env
#    ports:
#      - 5432:5432

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: backend
    container_name: backend
    command: bash -c "sleep 4 && sh ./docker/entrypoint.sh"
    env_file:
      - ./docker/.env
    volumes:
      - .:/code
    ports:
      - 80:80
    ######### stdin_open and tty to debug
    stdin_open: true
    tty: true
    links:
      - db